# μ„μ‹ redis μ„Έν…
services:
  redis_container:
    image: redis:latest
    ports:
      - '6379:6379'

    volumes:
      - redis_data:/data

  openvidu-server:
    image: openvidu/openvidu-server-kms:latest
    ports:
      - '4443:4443'
    environment:
      - OPENVIDU_SECRET=${OPENVIDU_SECRET}
      - OPENVIDU_URL=${OPENVIDU_URL}

volumes:
  redis_data:
