name: deploy
on:
  push: { branches: ["dev"] }
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    concurrency: { group: deploy-backend, cancel-in-progress: true }
    steps:
      - run: bash ~/app/matetrip-backend/deploy.sh
